# Project: InfoManagementSys
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = delete.o find.o infile.o input.o main.o outfile.o output.o
LINKOBJ  = delete.o find.o infile.o input.o main.o outfile.o output.o
LIBS     = -L"D:/dev/Dev-Cpp/MinGW64/lib" -L"D:/dev/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/dev/Dev-Cpp/MinGW64/include" -I"D:/dev/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/dev/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/dev/Dev-Cpp/MinGW64/include" -I"D:/dev/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/dev/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/dev/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = InfoManagementSys.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

delete.o: delete.cpp
	$(CPP) -c delete.cpp -o delete.o $(CXXFLAGS)

find.o: find.cpp
	$(CPP) -c find.cpp -o find.o $(CXXFLAGS)

infile.o: infile.cpp
	$(CPP) -c infile.cpp -o infile.o $(CXXFLAGS)

input.o: input.cpp
	$(CPP) -c input.cpp -o input.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

outfile.o: outfile.cpp
	$(CPP) -c outfile.cpp -o outfile.o $(CXXFLAGS)

output.o: output.cpp
	$(CPP) -c output.cpp -o output.o $(CXXFLAGS)
